export const mockUsers = [
  {
    id: 1,
    name: "Sarah Anderson",
    profession: "Product Designer",
    trustScore: 4.8,
    verified: true,
    avatar: "SA",
    category: "designers",
  },
  {
    id: 2,
    name: "Alex Chen",
    profession: "Full Stack Developer",
    trustScore: 4.9,
    verified: true,
    avatar: "AC",
    category: "developers",
  },
  {
    id: 3,
    name: "Emma Wilson",
    profession: "Content Writer",
    trustScore: 4.7,
    verified: true,
    avatar: "EW",
    category: "writers",
  },
  {
    id: 4,
    name: "Marcus Johnson",
    profession: "Startup Founder",
    trustScore: 4.6,
    verified: true,
    avatar: "MJ",
    category: "entrepreneurs",
  },
  {
    id: 5,
    name: "Lisa Park",
    profession: "UI/UX Designer",
    trustScore: 4.8,
    verified: true,
    avatar: "LP",
    category: "designers",
  },
  {
    id: 6,
    name: "David Kumar",
    profession: "Backend Engineer",
    trustScore: 4.9,
    verified: true,
    avatar: "DK",
    category: "developers",
  },
  {
    id: 7,
    name: "Rachel Green",
    profession: "Technical Writer",
    trustScore: 4.7,
    verified: true,
    avatar: "RG",
    category: "writers",
  },
  {
    id: 8,
    name: "James Miller",
    profession: "Product Manager",
    trustScore: 4.8,
    verified: true,
    avatar: "JM",
    category: "entrepreneurs",
  },
  {
    id: 9,
    name: "Sophie Turner",
    profession: "Graphic Designer",
    trustScore: 4.6,
    verified: true,
    avatar: "ST",
    category: "designers",
  },
]
